# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SDK Test run

on:
  push:
    branches: [ TP-10343 ]
  pull_request:
    branches: [ TP-10343 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml

  sdk-integration-test:
    env:
      appKey: ${{ secrets.APP_KEY }}
      appId: ${{ secrets.APP_ID }}
      userId: ${{ secrets.USER_ID }}
      supplierId: ${{ secrets.SUPPLIER_ID }}
    name: SDK E2E Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout SDK (PR branch)
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
          distribution: temurin

      - name: Build and install SDK to local Maven repo
        run: mvn clean install -DskipTests

      - name: Get SDK version from pom.xml
        id: get-version
        run: |
            VERSION=$(grep -m1 '<version>' pom.xml | sed -E 's/.*<version>(.*)<\/version>.*/\1/')
            echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Clone sdk-test repo
        run: git clone https://github.com/TelQ/sdk-test.git ../sdk-test

      - name: Replace SDK version in sdk-test POM
        run: |
          cd ../sdk-test
          sed -i "0,/<groupId>com.telqtele<\/groupId>/{n;s|<version>.*</version>|<version>${{ steps.get-version.outputs.version }}</version>|}" pom.xml

      - name: Run sdk-test with local SDK
        run: |
          cd ../sdk-test
          mvn clean test