# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SDK Test run

on:
  push:
    branches: [ TP-10343 ]
  pull_request:
    branches: [ TP-10343 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml

  sdk-integration-test:
    name: SDK E2E Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout SDK (PR branch)
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
          distribution: temurin

      - name: Build and install SDK to local Maven repo
        run: mvn clean install -DskipTests

      - name: Clone sdk-test repo
        run: git clone https://github.com/TelQ/sdk-test.git ../sdk-test

      - name: Run sdk-test with local SDK
        run: |
          cd ../sdk-test
          mvn clean test